FROM byscontrol/meteord:base
MAINTAINER ByS Control "info@bys-control.com.ar"

COPY scripts $METEORD_DIR
RUN METEOR_RELEASE=1.3.2.4 bash $METEORD_DIR/lib/install_meteor.sh
ONBUILD COPY ./ /app
ONBUILD ARG DEVELOPMENT=''
ONBUILD RUN DEVELOPMENT=$DEVELOPMENT bash $METEORD_DIR/on_build.sh